"""add user profile fields

Revision ID: 0a44168fac2c
Revises: 
Create Date: 2026-04-27 15:43:44.599704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a44168fac2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_columns = [col['name'] for col in inspector.get_columns('users')]
    
    columns_to_add = {
        'phone': sa.Column('phone', sa.String(length=20), nullable=True),
        'school': sa.Column('school', sa.String(length=255), nullable=True),
        'grade': sa.Column('grade', sa.String(length=50), nullable=True),
        'major': sa.Column('major', sa.String(length=255), nullable=True),
        'gpa': sa.Column('gpa', sa.Float(), nullable=True),
        'sat': sa.Column('sat', sa.Integer(), nullable=True),
        'grad_year': sa.Column('grad_year', sa.Integer(), nullable=True),
        'interests': sa.Column('interests', sa.Text(), nullable=True),
        'activities': sa.Column('activities', sa.Text(), nullable=True),
        'path': sa.Column('path', sa.String(length=100), nullable=True),
    }
    
    for col_name, col_def in columns_to_add.items():
        if col_name not in existing_columns:
            op.add_column('users', col_def)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'path')
    op.drop_column('users', 'activities')
    op.drop_column('users', 'interests')
    op.drop_column('users', 'grad_year')
    op.drop_column('users', 'sat')
    op.drop_column('users', 'gpa')
    op.drop_column('users', 'major')
    op.drop_column('users', 'grade')
    op.drop_column('users', 'school')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
