"""add user profile fields

Revision ID: 0a44168fac2c
Revises: 
Create Date: 2026-04-27 15:43:44.599704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a44168fac2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('school', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('grade', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('major', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('gpa', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('sat', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('grad_year', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('interests', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('activities', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('path', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'path')
    op.drop_column('users', 'activities')
    op.drop_column('users', 'interests')
    op.drop_column('users', 'grad_year')
    op.drop_column('users', 'sat')
    op.drop_column('users', 'gpa')
    op.drop_column('users', 'major')
    op.drop_column('users', 'grade')
    op.drop_column('users', 'school')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
