"""add user profile image fields

Revision ID: dcd51fe43b29
Revises: 0a44168fac2c
Create Date: 2026-04-27 17:42:02.672440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd51fe43b29'
down_revision: Union[str, Sequence[str], None] = '0a44168fac2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_columns = [col['name'] for col in inspector.get_columns('users')]
    
    if 'profile_image' not in existing_columns:
        op.add_column('users', sa.Column('profile_image', sa.String(length=255), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    # ### end Alembic commands ###
